### ISSUE TITLE
Improve website on mobile

### ISSUE THREAD

**Issue by odysseuskir** [simplified-coding/simplified-coding.github.io#74]
Our website isn't looking too good on mobile. Many issues occur that worsen the experience of users who get into the website for the first time using their phones. Some of these issues include:

- Icons in the navbar not fitting in
- A bug where a dark box appears on the right of the screen
- The lesson cards on a course page are way too thin
- Cards are stuck on the sides of the screen

This does NOT include the Simplified Coding editor, as it is only usable on a desktop.
```[tasklist]
### Tasks
- [x] Icons in the navbar not fitting in
- [x] A bug where a dark box appears on the right of the screen
- [ ] The lesson cards on a course page are way too thin
- [x] Cards are stuck on the sides of the screen
```
